###########################################################################################################################################################
# Python Script to segragating the test code files and application code files based on the text files generated by TestCodeFilter.py.
# These text files contain the test and application code paths. This script will create two folders separately for test and application files. 
# Authored by: Navneet Kaushal
# Graduate Student, Master of Engineering, Carleton University, Canada
# December, 2018
###########################################################################################################################################################

import os
import shutil

directory_name = input("Please enter the path: ")
newfolder_t = "TstFiles"
destroot_t = directory_name + newfolder_t
newfolder_a = "AppFiles"
destroot_a = directory_name + newfolder_a
os.chdir(directory_name)
file_list_t = "tfile.txt"
file_list_a = "afile.txt"
status = ""


try:
    os.mkdir(newfolder_t)
except OSError as e1:
    pass
status = "Copying test files..."
print(status)
with open(file_list_t) as ft:
    for srcfile_path_t in ft:
        srcfile_path_t = srcfile_path_t.strip()
        srcfile_t = os.path.split(srcfile_path_t)[1]
        destdir_t = os.path.join(destroot_t, srcfile_t)
        shutil.copy(srcfile_path_t, destdir_t)
status = "Test Files copied successfully."
print(status)
try:
    os.mkdir(newfolder_a)
except OSError as e2:
    pass
status = "Copying application files..."
print(status)

with open(file_list_a) as fa:
    for srcfile_path_a in fa:
        srcfile_path_a = srcfile_path_a.strip()
        srcfile_a = os.path.split(srcfile_path_a)[1]
        destdir_a = os.path.join(destroot_a, srcfile_a)
        shutil.copy(srcfile_path_a, destdir_a)
status = "Application Files copied successfully."
print(status)
